# Generated by Django 4.1.1 on 2022-11-12 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_type', models.CharField(choices=[('Cash', 'Cash'), ('Saving', 'Saving'), ('Credit card', 'credit Card')], default='Cash', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.transaction')),
                ('is_expense', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Rent', 'Rent'), ('Bill', 'Bill'), ('Entertainment', 'Entertainment'), ('Shopping', 'Shopping'), ('Internal Transfer', 'Internal Transfer'), ('Other', 'Other')], max_length=40)),
            ],
            bases=('account.transaction',),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.transaction')),
                ('is_income', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('Salary', 'Salary'), ('Investment', 'Investment'), ('Online Shop', 'Online Shop'), ('Internal Transfer', 'Internal Transfer'), ('Other', 'Other')], max_length=40)),
            ],
            bases=('account.transaction',),
        ),
        migrations.CreateModel(
            name='CustomIncome',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.transaction')),
                ('custom_category', models.CharField(max_length=40)),
                ('is_income', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('account.transaction',),
        ),
        migrations.CreateModel(
            name='CustomExpense',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.transaction')),
                ('custom_category', models.CharField(max_length=40)),
                ('is_expense', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('account.transaction',),
        ),
    ]
