# Generated by Django 4.1.4 on 2022-12-26 10:12

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('account_type', models.CharField(choices=[('Cash', 'Cash'), ('Saving', 'Saving'), ('Investment', 'Investment'), ('Credit card', 'Credit Card')], default='Cash', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.bankaccount')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.transaction')),
                ('nature', models.CharField(default='expense', editable=False, max_length=10)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Rent', 'Rent'), ('Bill', 'Bill'), ('Entertainment', 'Entertainment'), ('Shopping', 'Shopping'), ('Manual adjustment', 'Manual adjustment'), ('Other', 'Other')], max_length=40)),
            ],
            options={
                'ordering': ['-date'],
            },
            bases=('account.transaction',),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.transaction')),
                ('nature', models.CharField(default='income', editable=False, max_length=10)),
                ('category', models.CharField(choices=[('Salary', 'Salary'), ('Investment', 'Investment'), ('Online Shop', 'Online Shop'), ('Manual adjustment', 'Manual adjustment'), ('Other', 'Other')], max_length=40)),
            ],
            options={
                'ordering': ['-date'],
            },
            bases=('account.transaction',),
        ),
    ]
