# Generated by Django 4.1.4 on 2022-12-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='total_amount',
            new_name='balance',
        ),
    ]
