# Generated by Django 4.1.1 on 2022-11-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customexpense',
            name='is_expense',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='is_expense',
        ),
        migrations.AddField(
            model_name='customexpense',
            name='is_income',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_income',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='customincome',
            name='is_income',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='income',
            name='is_income',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
