# Generated by Django 4.1.1 on 2022-11-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customexpense_is_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customexpense',
            name='is_income',
            field=models.CharField(default='expense', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='customincome',
            name='is_income',
            field=models.CharField(default='income', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_income',
            field=models.CharField(default='expense', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='is_income',
            field=models.CharField(default='income', editable=False, max_length=10),
        ),
    ]
