# Generated by Django 4.1.4 on 2022-12-25 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_uuid_bankaccount_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='uuid',
            new_name='id',
        ),
    ]
