# Generated by Django 4.1.1 on 2022-12-12 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_alter_bankaccount_options_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customexpense',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customincome',
            name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
