# Generated by Django 4.1.4 on 2023-01-10 13:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('load_time', models.DateTimeField(auto_now_add=True)),
                ('leave_time', models.DateTimeField(auto_now=True, null=True)),
                ('screen_height', models.CharField(max_length=20, null=True)),
                ('screen_width', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
