# Generated by Django 4.1.4 on 2023-01-11 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=254, null=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='traffic_tracker.traffictracker')),
            ],
        ),
    ]
